<?xml version='1.0' encoding='utf-8'?>
<testsuites name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug" tests="24" failures="12" errors="0" time="51.758"><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[Arrays]" tests="2" failures="1" errors="0" skipped="0" time="5.989"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[Arrays]" time="5.983" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[Arrays]" time="0.006"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-2 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[BasicTypes]" tests="2" failures="1" errors="0" skipped="0" time="3.356"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[BasicTypes]" time="3.354" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[BasicTypes]" time="0.003"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-4 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[BoundedSequences]" tests="2" failures="1" errors="0" skipped="0" time="3.219"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[BoundedSequences]" time="3.217" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[BoundedSequences]" time="0.003"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-6 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[Builtins]" tests="2" failures="1" errors="0" skipped="0" time="3.211"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[Builtins]" time="3.209" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[Builtins]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-8 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[Constants]" tests="2" failures="1" errors="0" skipped="0" time="3.245"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[Constants]" time="3.243" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[Constants]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-10 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[Defaults]" tests="2" failures="1" errors="0" skipped="0" time="3.158"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[Defaults]" time="3.156" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[Defaults]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-12 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[Empty]" tests="2" failures="1" errors="0" skipped="0" time="5.23"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[Empty]" time="5.228" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[Empty]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-14 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[MultiNested]" tests="2" failures="1" errors="0" skipped="0" time="5.884"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[MultiNested]" time="5.882" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[MultiNested]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-16 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[Nested]" tests="2" failures="1" errors="0" skipped="0" time="5.908"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[Nested]" time="5.906" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[Nested]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-18 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[Strings]" tests="2" failures="1" errors="0" skipped="0" time="3.22"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[Strings]" time="3.218" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[Strings]" time="0.003"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-20 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[UnboundedSequences]" tests="2" failures="1" errors="0" skipped="0" time="3.22"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[UnboundedSequences]" time="3.217" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[UnboundedSequences]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-22 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.launch_tests[WStrings]" tests="2" failures="1" errors="0" skipped="0" time="6.116"><testcase classname="test_communication.TestPublisherSubscriber" name="test_subscriber_terminates_in_a_finite_amount_of_time[WStrings]" time="6.114" /><testcase classname="test_communication.TestPublisherSubscriberAfterShutdown" name="test_processes_finished_gracefully[WStrings]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_publisher_subscriber__rclpy__rmw_opendds_cpp_Debug.py&quot;, line 74, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_subscriber-24 exited with code -11&#10;" /></testcase></testsuite></testsuites>