<?xml version='1.0' encoding='utf-8'?>
<testsuites name="test_communication.test_requester_replier__rclpy__rclcpp__rmw_opendds_cpp_Debug" tests="6" failures="3" errors="0" time="17.601"><testsuite name="test_communication.test_requester_replier__rclpy__rclcpp__rmw_opendds_cpp_Debug.launch_tests[Arrays]" tests="2" failures="1" errors="0" skipped="0" time="5.727"><testcase classname="test_communication.TestRequesterReplier" name="test_requester_finishes_in_a_finite_amount_of_time[Arrays]" time="5.723" /><testcase classname="test_communication.TestRequesterReplierAfterShutdown" name="test_processes_finished_gracefully[Arrays]" time="0.003"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_requester_replier__rclpy__rclcpp__rmw_opendds_cpp_Debug.py&quot;, line 75, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_requester-2 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_requester_replier__rclpy__rclcpp__rmw_opendds_cpp_Debug.launch_tests[BasicTypes]" tests="2" failures="1" errors="0" skipped="0" time="5.974"><testcase classname="test_communication.TestRequesterReplier" name="test_requester_finishes_in_a_finite_amount_of_time[BasicTypes]" time="5.971" /><testcase classname="test_communication.TestRequesterReplierAfterShutdown" name="test_processes_finished_gracefully[BasicTypes]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_requester_replier__rclpy__rclcpp__rmw_opendds_cpp_Debug.py&quot;, line 75, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_requester-4 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_requester_replier__rclpy__rclcpp__rmw_opendds_cpp_Debug.launch_tests[Empty]" tests="2" failures="1" errors="0" skipped="0" time="5.901"><testcase classname="test_communication.TestRequesterReplier" name="test_requester_finishes_in_a_finite_amount_of_time[Empty]" time="5.899" /><testcase classname="test_communication.TestRequesterReplierAfterShutdown" name="test_processes_finished_gracefully[Empty]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_requester_replier__rclpy__rclcpp__rmw_opendds_cpp_Debug.py&quot;, line 75, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_requester-6 exited with code -11&#10;" /></testcase></testsuite></testsuites>