<?xml version='1.0' encoding='utf-8'?>
<testsuites name="test_communication.test_action_client_server__rclpy__rclcpp__rmw_opendds_cpp_Debug" tests="4" failures="2" errors="0" time="12.447"><testsuite name="test_communication.test_action_client_server__rclpy__rclcpp__rmw_opendds_cpp_Debug.launch_tests[Fibonacci]" tests="2" failures="1" errors="0" skipped="0" time="6.171"><testcase classname="test_communication.TestActionClientServer" name="test_client_finishes_in_a_finite_amount_of_time[Fibonacci]" time="6.167" /><testcase classname="test_communication.TestActionClientServerAfterShutdown" name="test_processes_finished_gracefully[Fibonacci]" time="0.004"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_action_client_server__rclpy__rclcpp__rmw_opendds_cpp_Debug.py&quot;, line 75, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_action_client-2 exited with code -11&#10;" /></testcase></testsuite><testsuite name="test_communication.test_action_client_server__rclpy__rclcpp__rmw_opendds_cpp_Debug.launch_tests[NestedMessage]" tests="2" failures="1" errors="0" skipped="0" time="6.276"><testcase classname="test_communication.TestActionClientServer" name="test_client_finishes_in_a_finite_amount_of_time[NestedMessage]" time="6.275" /><testcase classname="test_communication.TestActionClientServerAfterShutdown" name="test_processes_finished_gracefully[NestedMessage]" time="0.002"><failure message="Traceback (most recent call last):&#10;  File &quot;/opt/workspace/build/test_communication/test_action_client_server__rclpy__rclcpp__rmw_opendds_cpp_Debug.py&quot;, line 75, in test_processes_finished_gracefully&#10;    launch_testing.asserts.assertExitCodes(&#10;  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py&quot;, line 62, in assertExitCodes&#10;    assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(&#10;AssertionError: Proc test_action_client-4 exited with code -11&#10;" /></testcase></testsuite></testsuites>